#!/bin/bash

echo "Starting to initialize a new dev box ...";

CHEF_DOWNLOAD="chef_download";

cd ~;
if [ -a $CHEF_DOWNLOAD ]
then
    rm -rf $CHEF_DOWNLOAD;
fi
mkdir $CHEF_DOWNLOAD;
cd $CHEF_DOWNLOAD;
echo "######## Downloading ChefDK";
wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_1.0.3-1_amd64.deb
echo "######## Installing ChefDK";
sudo dpkg -i chefdk_1.0.3-1_amd64.deb
echo "######## Cleanup";
cd ~;
rm -rf $CHEF_DOWNLOAD;
echo "######## Setup completed";
