Metrics/LineLength:
  Max: 120

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
